version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    #ports:
    #  - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - /mnt/volume/plex-raspberry/plex-config:/config
      - /mnt/volume/plex-raspberry/downloads/tv:/tv
      - /mnt/volume/plex-raspberry/downloads/movies:/movies
    restart: unless-stopped

  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader2
    network_mode: host
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=America/Lima
      - LANG=es_PE.UTF-8
    #ports:
    #  - "5800:5800"
    volumes:
      - "/mnt/volume/plex-raspberry/jdownloader2-config:/config:rw"
      - "/mnt/volume/plex-raspberry/downloads:/output:rw"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - WEBUI_PORT=8080
    volumes:
      - /mnt/volume/plex-raspberry/qbittorrent-config:/config
      - /mnt/volume/plex-raspberry/downloads:/downloads
    #ports:
    #  - 8080:8080
    #  - 6881:6881
    #  - 6881:6881/udp
    restart: unless-stopped

  filebrowser:
    image: hurlenko/filebrowser
    #user: "${UID}:${GID}"
    ports:
      - 80:8080
    volumes:
      - /mnt/volume/plex-raspberry/downloads:/data
      - /mnt/volume/plex-raspberry/filebrowser-config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
